# Utilise OpenJDK 21
FROM openjdk:21-jdk-slim

# Répertoire de travail
WORKDIR /app

# Copier le jar construit par Maven
COPY target/*.jar app.jar

# Exposer le port de l'application
EXPOSE 8080

# Lancer le jar
ENTRYPOINT ["java", "-jar", "app.jar"]
